language: java
jdk:
    - oraclejdk8
notifications:
    slack: csu2017sp314:gxRwKuS4JI730yuYXGOiyUZ2
language: java
jdk:
  - oraclejdk8

after_success:
  - mvn clean test jacoco:report coveralls:report
